[theme]
base = "light"
primaryColor = "#6366f1"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"

[server]
[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 10000
maxUploadSize = 10

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
